[build]
  # Build command for Next.js
  command = "npm run build"
  # Publish directory for Next.js (Netlify will automatically detect this)
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for Next.js SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
