[build]
  # Build command for Next.js
  command = "npm run build"
  # Publish directory for Next.js
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure static assets are served correctly
[build]
  # Build command for Next.js
  command = "npm run build"
  # Publish directory for Next.js
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images and other static files from public folder
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"
