[build]
  # Build command for Next.js
  command = "npm run build"
  # Publish directory for Next.js
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Environment
  NODE_ENV = "production"

# Environment variables (these will be overridden by Netlify Environment Variables)
[build.environment]
  NEXT_PUBLIC_GEMINI_API_KEY = "$NEXT_PUBLIC_GEMINI_API_KEY"
  DATABASE_URL = "$DATABASE_URL"
  DIRECT_URL = "$DIRECT_URL"
  JWT_SECRET = "$JWT_SECRET"
  REFRESH_SECRET = "$REFRESH_SECRET"
  EMAIL_HOST = "smtp.gmail.com"
  EMAIL_PORT = "587"
  EMAIL_USER = "$EMAIL_USER"
  EMAIL_PASS = "$EMAIL_PASS"
  FROM_EMAIL = "$FROM_EMAIL"

# Redirect rules for Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images and other assets
[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
